#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2026 John Garry
#
# Test NVMe multipath nvme-generic cdev lifetime behaves as expected.

. tests/nvme/rc

DESCRIPTION="NVMe multipath cdev lifetime test"
CHECK_DMESG=1

requires() {
	_nvme_requires
	_have_loop
	_have_module_param_value nvme_core multipath Y
	_require_nvme_trtype_is_fabrics
	_have_kernel_options KASAN
}

set_conditions() {
	_set_nvme_trtype "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local nvmedev
	_nvmet_target_setup

	_nvme_connect_subsys

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")

	nvmegeneric=$(_nvme_find_subsys_nvme_generic)

	# nvme-delay-ioctl will open the nvme-generic cdev, sleep, and then
	# issue an ioctl.
	# We tear down the nvme-subsystem in the foreground so we can catch
	# if the ioctl triggers a use-after-free KASAN warn.
	src/nvme-delay-ioctl "/dev/$nvmegeneric" &
	sleep 0.5
	_nvme_disconnect_ctrl "${nvmedev}"
	_nvmet_target_cleanup
	wait < <(jobs -p)

	echo "Test complete"
}
