#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2025 Oracle and/or its affiliates
#
# Test SCSI Atomic Writes with MD devices

. tests/scsi/rc
. common/scsi_debug
. common/xfs

DESCRIPTION="test md atomic writes"
QUICK=1

requires() {
	_have_kver 6 14 0
	_have_driver scsi_debug
}

test() {
	local scsi_debug_atomic_wr_max_length
	local scsi_debug_atomic_wr_gran
	local scsi_sysfs_atomic_max_bytes
	local scsi_sysfs_atomic_unit_max_bytes
	local scsi_sysfs_atomic_unit_min_bytes
	local md_atomic_max_bytes
	local md_atomic_min_bytes
	local md_sysfs_max_hw_sectors_kb
	local md_max_hw_bytes
	local md_chunk_size
	local md_chunk_size_bytes
	local md_sysfs_logical_block_size
	local md_sysfs_atomic_max_bytes
	local md_sysfs_atomic_unit_max_bytes
	local md_sysfs_atomic_unit_min_bytes
	local bytes_to_write
	local bytes_written
	local test_desc
	local scsi_0
	local scsi_1
	local scsi_2
	local scsi_3
	local scsi_dev_sysfs
	local md_dev
	local md_dev_sysfs
	local scsi_debug_params=(
		delay=0
		atomic_wr=1
		num_tgts=1
		add_host=4
		per_host_store=true
	)

	echo "Running ${TEST_NAME}"

	if ! _configure_scsi_debug "${scsi_debug_params[@]}"; then
		return 1
	fi

	scsi_0="${SCSI_DEBUG_DEVICES[0]}"
	scsi_1="${SCSI_DEBUG_DEVICES[1]}"
	scsi_2="${SCSI_DEBUG_DEVICES[2]}"
	scsi_3="${SCSI_DEBUG_DEVICES[3]}"

	_md_atomics_test "${SCSI_DEBUG_DEVICES[0]}" "${SCSI_DEBUG_DEVICES[1]}" "${SCSI_DEBUG_DEVICES[2]}" "${SCSI_DEBUG_DEVICES[3]}"

	_exit_scsi_debug

	echo "Test complete"
}
