#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2025 Oracle and/or its affiliates
#
# Test NMVe Atomic Writes with MD devices

. tests/nvme/rc
. common/xfs

DESCRIPTION="test md atomic writes for NVMe drives"
QUICK=1

requires() {
	_have_kver 6 14 0
	_have_program mdadm
	_nvme_requires
	_have_program nvme
	_have_xfs_io_atomic_write
	_have_driver raid0
	_have_driver raid1
	_have_driver raid10
}

test() {
	local ns
	local testdev_count=0
	declare -A NVME_TEST_DEVS
	declare -A NVME_TEST_DEVS_SYSFS

	echo "Running test ${TEST_NAME}"

	nvme_0="${TEST_DEVS[0]}"
	nvme_1="${TEST_DEVS[1]}"
	nvme_2="${TEST_DEVS[2]}"
	
	echo "nvme_0="$nvme_0
	echo "nvme_1="$nvme_1
	echo "nvme_2="$nvme_2

	for i in "${!TEST_DEV_SYSFS_DIRS[@]}"; do
		TEST_DEV=${TEST_DEV_SYSFS_DIRS[$i]}
		echo "looping b0 TEST_DEV_SYSFS_DIRS and found i="$i" TEST_DEV="$TEST_DEV
		if readlink -f "$TEST_DEV" | grep -q nvme; then
			echo "looping b1 good i="$i" TEST_DEV="$TEST_DEV
			NVME_TEST_DEVS["$testdev_count"]="$i";
			NVME_TEST_DEVS_SYSFS["$testdev_count"]="$TEST_DEV";
			echo "looping b2b good NVME_TEST_DEVS="$NVME_TEST_DEVS[$testdev_count]" testdev_count="$testdev_count
			echo "looping b2c good NVME_TEST_DEVS_SYSFS="$NVME_TEST_DEVS_SYSFS[$testdev_count]" testdev_count="$testdev_count
			let testdev_count=testdev_count+1;
		else
			echo "looping b3 bad "$i
		fi
	done

	for i in "${!NVME_TEST_DEVS[@]}"; do
		NVME_TEST_DEV="${NVME_TEST_DEVS[$i]}"
		echo "looping d NVME_TEST_DEVS and found i="$i" NVME_TEST_DEV="$NVME_TEST_DEV
	done
	for i in "${!NVME_TEST_DEVS_SYSFS[@]}"; do
		NVME_TEST_DEV_SYSFS="${NVME_TEST_DEVS_SYSFS[$i]}"
		echo "looping e NVME_TEST_DEV_SYSFS and found i="$i" NVME_TEST_DEV_SYSFS="$NVME_TEST_DEV_SYSFS
	done


	for ((i = 0; i < ${#NVME_TEST_DEVS[@]}; ++i)); do
		# bash arrays are 0-indexed
		position=$(( $i + 1 ))
		TEST_DEV_SYSFS="${NVME_TEST_DEVS_SYSFS[$i]}"
		TEST_DEV="${NVME_TEST_DEVS[$i]}"
		echo "x $position,${NVME_TEST_DEVS[$i]},${NVME_TEST_DEVS_SYSFS[$i]}"
		echo "y TEST_DEV_SYSFS="$TEST_DEV_SYSFS
		echo "z TEST_DEV="$TEST_DEV
		_require_device_support_atomic_writes
	done

	echo "testdev_count="$testdev_count

	if [[ $testdev_count -lt 4 ]]; then
		echo "testdev_count not ge 4"
		SKIP_REASONS+=("requires at least 4 NVMe devices")
		return 1
	fi


	echo "Test complete"
}

