#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2025 Oracle and/or its affiliates
#
# Test NMVe Atomic Writes with MD devices

. tests/nvme/rc
. common/xfs

DESCRIPTION="test md atomic writes for NVMe drives"
QUICK=1

requires() {
	_have_kver 6 14 0
	_have_program mdadm
	_nvme_requires
	_have_program nvme
	_have_xfs_io_atomic_write
}

test() {
	local ns
	local testdev
	declare -A NVME_TEST_DEVS

	echo "Running test ${TEST_NAME}"

	nvme_0="${TEST_DEVS[0]}"
	nvme_1="${TEST_DEVS[1]}"
	nvme_2="${TEST_DEVS[2]}"
	
	echo "nvme_0="$nvme_0
	echo "nvme_1="$nvme_1
	echo "nvme_2="$nvme_2

	for i in "${!TEST_DEVS[@]}"; do
		TEST_DEV="${TEST_DEVS[$i]}"
		echo "looping a TEST_DEVS and found i="$i" TEST_DEV="$TEST_DEV
		

	done
	for i in "${!TEST_DEV_SYSFS_DIRS[@]}"; do
		TEST_DEV="${TEST_DEV_SYSFS_DIRS[$i]}"
		echo "looping b TEST_DEV_SYSFS_DIRS and found i="$i" TEST_DEV="$TEST_DEV

	done
	for i in "${!TEST_DEV_PART_SYSFS_DIRS[@]}"; do
		TEST_DEV="${TEST_DEV_PART_SYSFS_DIRS[$i]}"
		echo "looping c TEST_DEV_SYSFS_DIRS and found i="$i" TEST_DEV="$TEST_DEV
		if readlink -f "$i" | grep -q nvme; then
		echo "looping c good"
		else
		echo "looping c bad"
		fi
	done
	
		
	for ns in "/sys/block/nvme"* ; do
		# ignore nvme channel block devices
		#echo "looping and found0a="${ns}
		#echo "looping and found0b="$ns
		if ! [[ "${ns}" =~ nvme[0-9]+n[0-9]+ ]]; then
			continue
		fi
		echo "looping and found1a="${ns}
		echo "looping and found1b="$ns
	done
	echo "Test complete"
}

