#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2024 Ofir Gal
#
# Tests for md raid

. common/rc

group_requires() {
	_have_root
	_have_program mdadm
	_have_driver md-mod
}

declare -A MD_DEVICES

_md_atomics_test() {
	local md_atomic_max_bytes
	local md_atomic_min_bytes
	local md_sysfs_max_hw_sectors_kb
	local md_max_hw_bytes
	local md_chunk_size
	local md_chunk_size_bytes
	local md_sysfs_logical_block_size
	local md_sysfs_atomic_max_bytes
	local md_sysfs_atomic_unit_max_bytes
	local md_sysfs_atomic_unit_min_bytes
	local bytes_to_write
	local bytes_written
	local test_desc
	local md_dev
	local md_dev_sysfs
	local sysfs_atomic_unit_min_bytes
	local sysfs_atomic_unit_max_bytes
	local sysfs_atomic_max_bytes
	local sysfs_atomic_boundary_bytes
	local atomic_supported=1

	dev0=$1
	dev1=$2
	dev2=$3
	dev3=$4
	echo "running _md_atomics_test dev0="$dev0" dev1="$dev1" dev2="$dev2" dev3="$dev3
	unset MD_DEVICES
	MD_DEVICES=($dev0 $dev1 $dev2 $dev3);

	sysfs_atomic_unit_min_bytes=$(< "$dev0"/queue/atomic_write_unit_min_bytes);
	sysfs_atomic_unit_max_bytes=$(< "$dev0"/queue/atomic_write_unit_max_bytes);
	sysfs_atomic_max_bytes=$(< "$dev0"/queue/atomic_write_max_bytes);
	sysfs_atomic_boundary_bytes=$(< "$dev0"/queue/atomic_write_boundary_bytes);

#	echo "before sysfs_atomic_unit_min_bytes="$sysfs_atomic_unit_min_bytes
#	echo "before sysfs_atomic_unit_max_bytes="$sysfs_atomic_unit_max_bytes
#	echo "before sysfs_atomic_max_bytes="$sysfs_atomic_max_bytes
#	echo "before sysfs_atomic_boundary_bytes="$sysfs_atomic_boundary_bytes
#	echo "before atomic_supported="$atomic_supported
	for i in "${MD_DEVICES[@]}"; do
#		echo "llowwpiu MD_DEVICES="$i" unit min="$(< "$i"/queue/atomic_write_unit_min_bytes)
#		echo "llowwpiu MD_DEVICES="$i" unit max="$(< "$i"/queue/atomic_write_unit_max_bytes)
#		echo "llowwpiu MD_DEVICES="$i" max="$(< "$i"/queue/atomic_write_max_bytes)
#		echo "llowwpiu MD_DEVICES="$i" boundary="$(< "$i"/queue/atomic_write_boundary_bytes)
		if [[ $(< "$i"/queue/atomic_write_unit_min_bytes) -gt sysfs_atomic_unit_min_bytes ]]; then
			sysfs_atomic_unit_min_bytes=$(< "$i"/queue/atomic_write_unit_min_bytes)
		fi
		if [[ $(< "$i"/queue/atomic_write_unit_max_bytes) -lt sysfs_atomic_unit_max_bytes ]]; then
			sysfs_atomic_unit_max_bytes=$(< "$i"/queue/atomic_write_unit_max_bytes)
		fi
		if [[ $(< "$i"/queue/atomic_write_max_bytes) -lt sysfs_atomic_max_bytes ]]; then
			sysfs_atomic_max_bytes=$(< "$i"/queue/atomic_write_max_bytes)
		fi
		# The kernel only supports same boundary size for all devices in the array
		if [[ $(< "$i"/queue/atomic_write_boundary_bytes) -ne sysfs_atomic_boundary_bytes ]]; then
			let atomic_supported=0;
		fi
	done

#	echo "after sysfs_atomic_unit_min_bytes="$sysfs_atomic_unit_min_bytes
#	echo "after sysfs_atomic_unit_max_bytes="$sysfs_atomic_unit_max_bytes
#	echo "after sysfs_atomic_max_bytes="$sysfs_atomic_max_bytes
#	echo "after sysfs_atomic_boundary_bytes="$sysfs_atomic_boundary_bytes
#	echo "after atomic_supported="$atomic_supported

	# We cannot support atomic writes for the array of devices supported
	# However we can still test that the stacked device does not support
	# atomic writes (which it shouldn't).
	if [[ atomic_supported -eq 0 ]]; then
		let sysfs_atomic_unit_min_bytes=0;
		let sysfs_atomic_unit_max_bytes=0;
		let sysfs_atomic_max_bytes=0;
		let sysfs_atomic_boundary_bytes=0;
	fi
	echo "finally sysfs_atomic_unit_min_bytes="$sysfs_atomic_unit_min_bytes
	echo "finally sysfs_atomic_unit_max_bytes="$sysfs_atomic_unit_max_bytes
	echo "finally sysfs_atomic_max_bytes="$sysfs_atomic_max_bytes
	echo "finally sysfs_atomic_boundary_bytes="$sysfs_atomic_boundary_bytes
	echo "finally atomic_supported="$atomic_supported

	for raid_level in 0 1 10; do
		echo "raid_level="$raid_level
		if [ "$raid_level" = 10 ]
		then
			echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
				--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
				/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
		else
			echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
				--raid-devices=2 --force \
				/dev/"${dev0}" /dev/"${dev1}" 2> /dev/null 1>&2
		fi

	
		mdadm --stop /dev/md/blktests_md  2> /dev/null 1>&2

	done
}
