#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2024 Ofir Gal
#
# Tests for md raid

. common/rc

group_requires() {
	_have_root
	_have_program mdadm
	_have_driver md-mod
}

declare -A MD_DEVICES

_md_atomics_test() {
	local md_atomic_unit_max
	local md_atomic_unit_min
	local md_sysfs_max_hw_sectors_kb
	local md_sysfs_max_hw
	local md_chunk_size
	local md_chunk_size
	local sysfs_logical_block_size
	local sysfs_atomic_write_max
	local sysfs_atomic_write_unit_max
	local sysfs_atomic_write_unit_min
	local bytes_to_write
	local bytes_written
	local test_desc
	local md_dev
	local md_dev_sysfs
	local expected_atomic_write_unit_min
	local expected_atomic_write_unit_max
	local expected_atomic_write_max
	local expected_atomic_write_boundary
	local expected_atomic_write_supported=1

	dev0=$1
	dev1=$2
	dev2=$3
	dev3=$4
	echo "running _md_atomics_test dev0="$dev0" dev1="$dev1" dev2="$dev2" dev3="$dev3
	unset MD_DEVICES
	MD_DEVICES=($dev0 $dev1 $dev2 $dev3);

	# Use the limits from the first device and then loop again to find lowest common supported
	expected_atomic_write_unit_min=$(< /sys/block/"$dev0"/queue/atomic_write_unit_min_bytes);
	expected_atomic_write_unit_max=$(< /sys/block/"$dev0"/queue/atomic_write_unit_max_bytes);
	expected_atomic_write_max=$(< /sys/block/"$dev0"/queue/atomic_write_max_bytes);
	expected_atomic_write_boundary=$(< /sys/block/"$dev0"/queue/atomic_write_boundary_bytes);

	for i in "${MD_DEVICES[@]}"; do
		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes) -gt expected_atomic_write_unit_min ]]; then
			expected_atomic_write_unit_min=$(< /sys/block/"$i"/queue/atomic_write_unit_min_bytes)
		fi
		if [[ $(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes) -lt expected_atomic_write_unit_max ]]; then
			expected_atomic_write_unit_max=$(< /sys/block/"$i"/queue/atomic_write_unit_max_bytes)
		fi
		if [[ $(< /sys/block/"$i"/queue/atomic_write_max_bytes) -lt expected_atomic_write_max ]]; then
			expected_atomic_write_max=$(< /sys/block/"$i"/queue/atomic_write_max_bytes)
		fi
		# The kernel only supports same boundary size for all devices in the array
		if [[ $(< /sys/block/"$i"/queue/atomic_write_boundary_bytes) -ne expected_atomic_write_boundary ]]; then
			let expected_atomic_write_supported=0;
		fi
	done


	# We cannot support atomic writes for the array of devices supported
	# However we can still test that the stacked device does not support
	# atomic writes (which it shouldn't).
	if [[ expected_atomic_write_supported -eq 0 ]]; then
		let expected_atomic_write_unit_min=0;
		let expected_atomic_write_unit_max=0;
		let expected_atomic_write_max=0;
		let expected_atomic_write_boundary=0;
	fi
	echo "finally expected_atomic_write_unit_min="$expected_atomic_write_unit_min
	echo "finally expected_atomic_write_unit_max="$expected_atomic_write_unit_max
	echo "finally expected_atomic_write_max="$expected_atomic_write_max
	echo "finally expected_atomic_write_boundary="$expected_atomic_write_boundary
	echo "finally expected_atomic_write_supported="$expected_atomic_write_supported

	for raid_level in 0 1 10; do
		# We loop for different chunk sizes, even though it is not relevant to RAID1
		chunk_gran=$(( "$expected_atomic_write_unit_max" / 4))
		if [ "$chunk_gran" -lt "$expected_atomic_write_unit_min" ]
		then
			chunk_gran=$expected_atomic_write_unit_min
		fi
		local chunk_multiple=1
		for step in `seq 1 6`
		do
			echo "chunky1 chunk_gran="$chunk_gran" raid_level="$raid_level" step="$step
			local md_expected_atomic_write_unit_min
			local md_expected_atomic_write_unit_max
			local md_expected_atomic_write_max
			local md_chunk_atomic_write_boundary

			if [ "$raid_level" = 0 ]
			then
				chunk_multiple=$step
			else
				chunk_multiple=$(( 2 * "$chunk_multiple"))
			fi
			md_chunk_size=$(( "$chunk_gran" * "$chunk_multiple"))
			echo "chunky2 md_chunk_size="$md_chunk_size" chunk_multiple="$chunk_multiple
			md_chunk_size_kb=$(( "$md_chunk_size" / 1024))

			# We may reassign these for RAID0/10
			let md_expected_atomic_write_unit_min=$expected_atomic_write_unit_min
			let md_expected_atomic_write_unit_max=$expected_atomic_write_unit_max
			let md_expected_atomic_write_max=$expected_atomic_write_max
			let md_expected_atomic_write_boundary=$expected_atomic_write_boundary

			if [ "$raid_level" = 0 ] || [ "$raid_level" = 10 ]
			then
				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
					 --chunk="${md_chunk_size_kb}"K \
					--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
					/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
				if [ "$expected_atomic_write_boundary" -gt 0 ]
				then
					echo "grace we have a boundary="$expected_atomic_write_boundary
				else
					echo "grace we have no boundary="$expected_atomic_write_boundary
				fi
			else
				echo y | mdadm --create /dev/md/blktests_md --level=$raid_level \
					--raid-devices=4 --force /dev/"${dev0}" /dev/"${dev1}" \
					/dev/"${dev2}" /dev/"${dev3}" 2> /dev/null 1>&2
			fi

			md_dev=$(readlink /dev/md/blktests_md | sed 's|\.\./||')
			md_dev_sysfs="/sys/devices/virtual/block/${md_dev}"

			sysfs_logical_block_size=$(< "${md_dev_sysfs}"/queue/logical_block_size)
			md_sysfs_max_hw_sectors_kb=$(< "${md_dev_sysfs}"/queue/max_hw_sectors_kb)
			md_sysfs_max_hw=$(( "$md_sysfs_max_hw_sectors_kb" * 1024 ))
			sysfs_atomic_write_max=$(< "${md_dev_sysfs}"/queue/atomic_write_max_bytes)
			sysfs_atomic_write_unit_max=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_max_bytes)
			sysfs_atomic_write_unit_min=$(< "${md_dev_sysfs}"/queue/atomic_write_unit_min_bytes)
			sysfs_atomic_write_boundary=$(< "${md_dev_sysfs}"/queue/atomic_write_boundary_bytes)
			echo "sysfs_atomic_write_boundary="$sysfs_atomic_write_boundary

			test_desc="TEST 1 RAID $raid_level - Verify md sysfs atomic attributes matches"
			if [ "$sysfs_atomic_write_unit_max" = "$md_expected_atomic_write_unit_max" ] &&
				[ "$sysfs_atomic_write_unit_min" = "$md_expected_atomic_write_unit_min" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail sysfs_atomic_write_unit_min="$sysfs_atomic_write_unit_min \
					"sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"md_expected_atomic_write_unit_min="$md_expected_atomic_write_unit_min \
					"md_expected_atomic_write_unit_max="$md_expected_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 2 RAID $raid_level - Verify sysfs atomic attributes"
			if [ "$md_sysfs_max_hw" -ge "$sysfs_atomic_write_max" ] &&
				[ "$sysfs_atomic_write_max" -ge "$sysfs_atomic_write_unit_max" ] &&
				[ "$sysfs_atomic_write_unit_max" -ge "$sysfs_atomic_write_unit_min" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail $md_sysfs_max_hw="$md_sysfs_max_hw \
					"sysfs_atomic_write_max="$sysfs_atomic_write_max \
					"sysfs_atomic_write_unit_min="$sysfs_atomic_write_unit_min \
					"sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 3 RAID $raid_level - Verify md sysfs_atomic_write_max is less than or equal "
			test_desc+="sysfs_atomic_write_max"
			if [ "$sysfs_atomic_write_max" -le "$expected_atomic_write_max" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail sysfs_atomic_write_max="$sysfs_atomic_write_max \
					"expected_atomic_write_max="$expected_atomic_write_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 4 RAID $raid_level - check sysfs atomic_write_unit_max_bytes =  expected_atomic_write_unit_max"
			if [ "$sysfs_atomic_write_unit_max" = "$expected_atomic_write_unit_max" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"expected_atomic_write_unit_max="$expected_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 5 RAID $raid_level - check sysfs atomic_write_unit_min_bytes = expected atomic_write_unit_min_bytes"
			if [ "$sysfs_atomic_write_unit_min" = "$expected_atomic_write_unit_min" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail sysfs_atomic_write_unit_min="$sysfs_atomic_write_unit_min \
					"expected_atomic_write_unit_min="$expected_atomic_write_unit_min \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 6 RAID $raid_level - check statx stx_atomic_write_unit_min"
			statx_atomic_write_unit_min=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_min")
			if [ "$statx_atomic_write_unit_min" = "$sysfs_atomic_write_unit_min" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail statx_atomic_write_unit_min="$statx_atomic_write_unit_min \
					"sysfs_atomic_write_unit_min="$sysfs_atomic_write_unit_min \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 7 RAID $raid_level - check statx stx_atomic_write_unit_max"
			statx_atomic_write_unit_max=$(run_xfs_io_xstat /dev/"$md_dev" "stat.atomic_write_unit_max")
			if [ "$statx_atomic_write_unit_max" = "$sysfs_atomic_write_unit_max" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail statx_atomic_write_unit_max="$statx_atomic_write_unit_max \
					"sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 8 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes with "
			test_desc+="RWF_ATOMIC flag - pwritev2 should be succesful"
			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$sysfs_atomic_write_unit_max")
			if [ "$bytes_written" = "$sysfs_atomic_write_unit_max" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail bytes_written="$bytes_written \
					"sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 9 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_max_bytes + 512 "
			test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should not be succesful"
			bytes_to_write=$(( "${sysfs_atomic_write_unit_max}" + 512 ))
			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
			if [ "$bytes_written" = "" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail bytes_written="$bytes_written \
					"bytes_to_write="$bytes_to_write \
					"sysfs_atomic_write_unit_max="$sysfs_atomic_write_unit_max \
					"md_chunk_size="$md_chunk_size
			fi

			test_desc="TEST 10 RAID $raid_level - perform a pwritev2 with size of sysfs_atomic_unit_min_bytes "
			test_desc+="with RWF_ATOMIC flag - pwritev2 should be succesful"
			bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$sysfs_atomic_write_unit_min")
			if [ "$bytes_written" = "$sysfs_atomic_write_unit_min" ]
			then
				echo "$test_desc - pass"
			else
				echo "$test_desc - fail bytes_written="$bytes_written \
					"sysfs_atomic_write_unit_min="$sysfs_atomic_write_unit_min \
					"md_chunk_size="$md_chunk_size
			fi

			bytes_to_write=$(( "${sysfs_atomic_write_unit_min}" - "${sysfs_logical_block_size}" ))
			test_desc="TEST 11 RAID $raid_level - perform a pwritev2 with a size of sysfs_atomic_unit_min_bytes - 512 "
			test_desc+="bytes with RWF_ATOMIC flag - pwritev2 should fail"
			if [ "$bytes_to_write" = 0 ]
			then
				echo "$test_desc - pass"
			else
				bytes_written=$(run_xfs_io_pwritev2_atomic /dev/"$md_dev" "$bytes_to_write")
				if [ "$bytes_written" = "" ]
				then
					echo "$test_desc - pass"
				else
					echo "$test_desc - fail bytes_written="$bytes_written \
						"bytes_to_write="$bytes_to_write \
						"md_chunk_size="$md_chunk_size
				fi
			fi
			mdadm --stop /dev/md/blktests_md  2> /dev/null 1>&2
			mdadm --zero-superblock /dev/"${dev0}"  2> /dev/null 1>&2
			mdadm --zero-superblock /dev/"${dev1}"  2> /dev/null 1>&2
			mdadm --zero-superblock /dev/"${dev2}"  2> /dev/null 1>&2
			mdadm --zero-superblock /dev/"${dev3}"  2> /dev/null 1>&2
		done
	done
}
